version: 0.0
Resources:
- myLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      Name: cdk-lambda-py # Nombre exacto de tu funci칩n Lambda
      Alias: dev # Alias que CodeDeploy gestionar치
      CurrentVersion: 26 # Obtiene la versi칩n actual de la funci칩n
