version: 0.0
Resources:
- myLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      Name: cdk-lambda-py
      Alias: dev # Usa el alias 'dev' en lugar de $LATEST
      CurrentVersion: !Ref "LambdaFunctionVersion" # O usa referencia a la versión si es necesario
