version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
    - ls
    - pip install -r requirements.txt
  build:
    commands:
    - zip -r function.zip . # Comprime todo el código y archivos
    - zip -g function.zip appspec.yml # Agrega el appspec.yml al zip

artifacts:
  files:
  - appspec.yml
  - function.zip
  discard-paths: yes
